spring:
    datasource:
          url: jdbc:mysql://localhost:3306/harlan_en?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#          url: jdbc:mysql://localhost/harlan_en?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: root
#          password: root
          #连接池的配置信息
          initialSize: 10
          minIdle: 10
          maxActive: 100
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
